export const CHAT_REQ_REQUEST = "CHAT_REQ_REQUEST";
export const CHAT_REQ_SUCCESS = "CHAT_REQ_SUCCESS";
export const CHAT_REQ_FAILURE = "CHAT_REQ_FAILURE";


export const CHAT_UPDATE_REQ = "CHAT_UPDATE_REQ";
export const CHAT_UPDATE_SUCCESS = "CHAT_UPDATE_SUCESS";
export const CHAT_UPDATE_FAILURE = "CHAT_UPDATE_FAILURE";

export const GETALLCHAT_REQ = "GETALLCHAT_REQ";
export const GETALLCHAT_REQ_SUCCESS = "GETALLCHAT_REQ_SUCCESS";
export const GETALLCHAT_REQ_FAILURE = "GETALLCHAT_REQ_FAILURE";

export const SWITCH_CHAT_REQ = "SWITCH_CHAT_REQ";
export const SWITCH_CHAT_SUCCESS = "SWITCH_CHAT_SUCCESS";
export const SWITCH_CHAT_FAILURE = "SWITCH_CHAT_FAILURE";

export const CREATE_CHAT_REQ = "CREATE_CHAT_REQ"
export const CREATE_CHAT_SUCESS = "CREATE_CHAT_SUCESS"
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE"
